global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'netpulse'
    static_configs:
      - targets: ['netpulse:8080']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: [node-exporter:9100]
